### ISSUE TITLE
Confused about transpose of constraint matrix

### ISSUE THREAD

**Issue by utkutpcgl** [EGiunchiglia/C-HMCNN#3]
Thanks for your work!
For the output of get_constr_out to be correct, should not we take the transpose of the constraint matrix? The constrain matrix contains the ancestors at the last dimension, however, we want an ancestor to take the maximum of its descendants. 
https://github.com/EGiunchiglia/C-HMCNN/blob/ae8026517357abb69972a1d06f6481497ce00617/main.py#L27

**Comment by EGiunchiglia** [comment]
Hi! Sorry for the delayed reply. 

I checked it and there were misleading comments in the main file. I have now changed them (plus I have added further clarifications). Let me know if that helps :)
